name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.5

      # 3. Cache modules para acelerar builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install dependencies
      - name: Install dependencies
        run: go mod download

      # 5. Run tests
      - name: Run tests
        run: go test ./... -v

      # 6. Linting
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.0
          args: run ./...

      # 7. Check formatting with gofmt
      - name: Check formatting with gofmt
        run: |
          if [[ -n $(gofmt -l .) ]]; then
            echo "Some files are not formatted properly. Run 'gofmt -w .' to fix."
            exit 1
          fi

      # 8. Security scan with gosec
      - name: Run gosec security scan
        uses: securego/gosec-action@v2
        with:
          args: ./...
