name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Verify formatting
        run: |
          echo "Checking formatting with gofmt..."
          gofmt_output=$(gofmt -l .)
          if [ -n "$gofmt_output" ]; then
            echo "Files not properly formatted:"
            echo "$gofmt_output"
            exit 1
          fi

      - name: Run Linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          $HOME/go/bin/golangci-lint run

      - name: Run Security Scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          $HOME/go/bin/gosec ./...

      - name: Build binaries
        run: |
          mkdir -p build
          for pkg in $(go list ./...); do
            name=$(basename $pkg)
            echo "Building $name..."
            go build -o build/$name $pkg
          done

      - name: Run Tests
        run: go test ./...