name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Verify formatting
        run: |
          echo "Checking formatting with gofmt..."
          gofmt_output=$(gofmt -l .)
          if [ -n "$gofmt_output" ]; then
            echo "Files not properly formatted:"
            echo "$gofmt_output"
            exit 1
          fi

      - name: Run Security Scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...

      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Build binaries
        run: |
          mkdir -p build
          go build -v -o build/ ./...
